import { GetServerSideProps, NextPage } from "next"
import Head from "next/head"

const Home:NextPage = () => {
   return (
      <>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         test
      </>
   )
}

export default Home

export const getServersideProps:GetServerSideProps =  async () =>{
   
   return {
      props: {

      }
   }
}