import { NextPage } from "next"
import Head from "next/head"
import { useAppSelector } from "~/store/hooks"
import { CampaignCard } from "~/components"

const Home:NextPage = () => {
   const { campaigns } = useAppSelector(state => state.contracts)
   
   return (
      <>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <main className="container mx-auto gap-4 mt-6 grid grid-cols-3">
            {campaigns.map(x=>(
               <CampaignCard
                  campaign={x}
                  key={x.address}
               />
            ))}
         </main>
      </>
   )
}

export default Home