import { NextPage } from "next"
import Head from "next/head"
import Layout from "../components/Layout"

const Home:NextPage = ({params}) => {
   return (
      <>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         test
      </>
   )
}
export default Home